#!/bin/bash
/home/alex/.xrandr
herbstclient detect_monitors
xsetroot -cursor_name left_ptr

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}


hc emit_hook reload

xsetroot -solid '#1d1f21'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Alt=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return        spawn   termite -e      tmux
hc keybind $Mod-Shift-Return  spawn   termite
hc keybind $Mod-b             spawn   chromium
hc keybind $Mod-e             spawn   rofi -show run
hc keybind $Mod-w             spawn   rofi -show window
hc keybind $Mod-m             spawn   nmcli_dmenu
hc keybind $Mod-o             spawn   /home/alex/scripts/pdfopen.sh

# basic movement
# focusing clients
# hc keybind $Mod-Left  focus left
# hc keybind $Mod-Down  focus down
# hc keybind $Mod-Up    focus up
# hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
# hc keybind $Mod-Shift-Left  shift left
# hc keybind $Mod-Shift-Down  shift down
# hc keybind $Mod-Shift-Up    shift up
# hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-Control-j  split   bottom  0.5
hc keybind $Mod-Control-l  split   right   0.5
hc keybind $Mod-Control-k  split   top     0.5
hc keybind $Mod-Control-h  split   left    0.5
hc keybind $Mod-Control-3  spawn   /home/alex/scripts/triple-split
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-a       resize left +$resizestep
hc keybind $Mod-s       resize down +$resizestep
hc keybind $Mod-d       resize up +$resizestep
hc keybind $Mod-f       resize right +$resizestep
# hc keybind $Mod-Control-Left    resize left +$resizestep
# hc keybind $Mod-Control-Down    resize down +$resizestep
# hc keybind $Mod-Control-Up      resize up +$resizestep
# hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Alt-space cycle_layout 1
hc keybind $Mod-space floating toggle
hc keybind $Alt-f fullscreen toggle
hc keybind $Mod-Shift-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

hc keybind XF86MonBrightnessUp     spawn   /home/alex/scripts/dbright      -i      5
hc keybind XF86MonBrightnessDown   spawn   /home/alex/scripts/dbright      -d      5
hc keybind XF86KbdBrightnessUp     spawn   kbdlight        up
hc keybind XF86KbdBrightnessDown   spawn   kbdlight        down
hc keybind XF86PowerOff            spawn   /home/alex/scripts/power-dmenu
hc keybind XF86AudioRaiseVolume    spawn   /home/alex/scripts/dvol -i      5
hc keybind XF86AudioLowerVolume    spawn   /home/alex/scripts/dvol -d      5
hc keybind XF86AudioMute           spawn   /home/alex/scripts/dvol -t
hc keybind XF86AudioPlay           spawn   mpc toggle
hc keybind XF86AudioNext           spawn   mpc next
hc keybind XF86AudioPrev           spawn   mpc prev


# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#373b41'
hc set frame_border_normal_color '#1d1f21'
hc set frame_bg_normal_color '#c5c8c6'
hc set frame_bg_active_color '#cc6666'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.active.color '#cc6666'
hc attr theme.normal.color '#c5c8c6'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#282a2e'
hc attr theme.active.outer_color '#cc6666'
hc attr theme.background_color '#1d1f21'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
