#!/bin/bash

#Customize this stuff
SECS="1"            # sleep $SECS
background="#525252"        # background colour of window
foreground="#dcdccc"        # foreground colour of text/icon
bar_fg="#dcdccc"    # foreground colour of volume bar
bar_bg="#1e2320"    # background colour of volume bar
XPOS="1675"          # horizontal positioning
YPOS="21"          # vertical positioning
HEIGHT="35"         # window height
WIDTH="180"         # window width
#ICON=~/.xmonad/dzen2/spkr_01.xbm
DISPLAY=:0

notify-send $(acpi -V | head -n 1 | cut -d ',' -f 2-3)
