#!/bin/bash

#Customize this stuff
SECS="1"            # sleep $SECS
background="#525252"        # background colour of window
foreground="#1e2320"        # foreground colour of text/icon
bar_fg="#dcdccc"    # foreground colour of volume bar
bar_bg="#1e2320"    # background colour of volume bar
XPOS="865"          # horizontal positioning
YPOS="1100"          # vertical positioning
HEIGHT="40"         # window height
WIDTH="190"         # window width
#HEIGHT="190"         # window height
#WIDTH="40"         # window width
BAR_WIDTH="165"     # width of volume bar
BAR_HEIGHT="15"     # height of volume bar
#BAR_HEIGHT="165"     # height of volume bar
#BAR_WIDTH="15"     # width of volume bar
#ICON=~/.xmonad/dzen2/spkr_01.xbm
FONT="-*-termsyn-*-*-*-*-*-*-*-*-*-*-*-*"

PIPE="/tmp/dvolpipe"

err() {
  echo "$1"
  exit 1
}



usage() {
  echo "usage: dbright [option] [argument]"
  echo
  echo "Options:"
  echo "     -i, --increase - increase brightness by \`argument'"
  echo "     -d, --decrease - decrease brightness by \`argument'"
  echo "     -h, --help     - display this"
  exit
}

#Argument Parsing
case "$1" in
  '-i'|'--increase')
    [ -z "$2" ] && err "No argument specified for increase."
    [ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    xbacklight + "$2"
    ;;
  '-d'|'--decrease')
    [ -z "$2" ] && err "No argument specified for decrease."
    [ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    xbacklight - "$2"
    ;;
  '-t'|'--toggle')
    ;;
  '-s')
    ;;
  ''|'-h'|'--help')
    usage
    ;;
  *)
    err "Unrecognized option \`$1', see dbrightness --help"
    ;;
esac

#Using named pipe to determine whether previous call still exists
#Also prevents multiple volume bar instances
if [ ! -e "$PIPE" ]; then
  mkfifo "$PIPE"
  (dzen2 -tw "$WIDTH" -h "$HEIGHT" -x "$XPOS" -y "$YPOS" -fn "$FONT" -bg "$background" -fg "$foreground" < "$PIPE" 
   rm -f "$PIPE") &
fi

#Feed the pipe!
(echo "$(xbacklight)" | gdbar -fg "$bar_fg" -bg "$bar_bg" -w "$BAR_WIDTH" -h "$BAR_HEIGHT" ; sleep "$SECS") > "$PIPE"
