#!/bin/bash

#Customize this stuff
IF="Master"         # audio channel: Master|PCM
SECS="1"            # sleep $SECS
background="#525252"        # background colour of window
foreground="#1e2320"        # foreground colour of text/icon
bar_fg="#dcdccc"    # foreground colour of volume bar
bar_bg="#1e2320"    # background colour of volume bar
XPOS="1615"          # horizontal positioning
YPOS="21"          # vertical positioning
#HEIGHT="40"         # window height
#WIDTH="190"         # window width
HEIGHT="190"         # window height
WIDTH="40"         # window width
#BAR_WIDTH="165"     # width of volume bar
#BAR_HEIGHT="15"     # height of volume bar
BAR_HEIGHT="165"     # height of volume bar
BAR_WIDTH="15"     # width of volume bar
#ICON=~/.xmonad/dzen2/spkr_01.xbm
FONT="-*-termsyn-*-*-*-*-*-*-*-*-*-*-*-*"
DZEN="dzen2 -tw $WIDTH -h $HEIGHT -x $XPOS -y $YPOS -fn $FONT -bg $background -fg $foreground"

PIPE="/tmp/dvolpipe"

err() {
  echo "$1"
  exit 1
}

background() {
  (echo "" | dzen2 -title-name background -w 60 -x 1645 -h 21 -p -e 'entertitle=exec:/home/alex/scripts/dvol --show;leavetitle=exec:/home/alex/scripts/dvol --hide' &) && sleep 0.1s && transset-df -n background 0 > /dev/null 2>&1
  exit
}

usage() {
  echo "usage: dvol [option] [argument]"
  echo
  echo "Options:"
  echo "     -i, --increase - increase volume by \`argument'"
  echo "     -d, --decrease - decrease volume by \`argument'"
  echo "     -t, --toggle   - toggle mute on and off"
  echo "     -h, --help     - display this"
  exit
}

show_bar() {
  #Using named pipe to determine whether previous call still exists
  #Also prevents multiple volume bar instances
  if [ ! -e "$PIPE" ]; then
    mkfifo "$PIPE"
    ($DZEN < "$PIPE" 
    rm -f "$PIPE") &
  fi
}

show() {
  AMIXOUT="$(amixer sget "$IF" | tail -n 1)"
  VOL="$(cut -d '[' -f 2 <<<"$AMIXOUT" | sed 's/%.*//g')"
  DZEN="$DZEN -p"
  show_bar
  (echo "$VOL" | gdbar -s v -fg "$bar_fg" -bg "$bar_bg" -sw "$BAR_WIDTH" -h "$BAR_HEIGHT" ; sleep 3) > "$PIPE"
  exit
}

hide() {
  pkill -f dzen2\ -tw > /dev/null 2>&1
  exit
}

#Argument Parsing
case "$1" in
  '-i'|'--increase')
    [ -z "$2" ] && err "No argument specified for increase."
    [ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    AMIXARG="${2}%+"
    ;;
  '-d'|'--decrease')
    [ -z "$2" ] && err "No argument specified for decrease."
    [ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    AMIXARG="${2}%-"
    ;;
  '-t'|'--toggle')
    AMIXARG="toggle"
    ;;
  '--show')
    show
    ;;
  '--hide')
    hide
    ;;
  '-b')
    background
    ;;
  '--temp')
    AMIXARG="0%-"
    SECS=3
    ;;
  ''|'-h'|'--help')
    usage
    ;;
  *)
    err "Unrecognized option \`$1', see dvol --help"
    ;;
esac

#Actual volume changing (readability low)
AMIXOUT="$(amixer set "$IF" "$AMIXARG" && killall -SIGUSR1 conky | tail -n 1)"
MUTE="$(cut -d '[' -f 4 <<<"$AMIXOUT")"
if [ "$MUTE" = "off]" ]; then
  VOL="0"
else
  VOL="$(cut -d '[' -f 2 <<<"$AMIXOUT" | sed 's/%.*//g')"
fi

show_bar

#Feed the pipe!
(echo "$VOL" | gdbar -s v -fg "$bar_fg" -bg "$bar_bg" -sw "$BAR_WIDTH" -h "$BAR_HEIGHT" ; sleep "$SECS") > "$PIPE"

