#!/bin/bash
source $(dirname $0)/config

# BATTERY ICONS:
#      

VOL=$(amixer -M get Master | tail -n 1 | grep -oE '[0-9]+%' | sed 's/%//')


bar_font() {
  if amixer get Master | grep '\[on\]' > /dev/null; then
    if [ "$VOL" -lt "50" ]; then
      ICON='%{F\#FF9c818e}%{F-}'
    else
      ICON='%{F\#FF9c818e}%{F-}'
    fi
  else
    ICON='%{F\#FFb45a5a}%{F-}'
  fi
}

# Create Bar
echo "$VOL"

