#!/usr/bin/env bash

pgrep -x sxhkd >/dev/null || sxhkd &

autostart() {
    ~/dotfiles/scripts/graphic-session
    wmname LG3D
}

export BROWSER=/usr/bin/firefox-nightly

autostart

for monitor in $(bspc query -M); do
    bspc monitor "$monitor" -d emacs web term chat games music logs idea video
done

bspc config border_width 3
bspc config window_gap 6

bspc config focus_follows_pointer true

bspc config split_ratio 0.67
bspc config borderless_monocle false
bspc config gapless_monocle false

### Colours
urgentBlue="#010081"
barbg="#C0C0C0"
# brightblack="#fffffe"
blue="#00AEB7"
brightblue="#9c9ba9"
vaporpink="#ff7faa"
black="#2d2d2d"
brightblack="#010303"
bspc config focused_border_color "$vaporpink"
bspc config active_border_color "$brightblack"
bspc config normal_border_color "$black"
bspc config presel_feedback_color "$barbg"

bspc rule -a Dunst layer='above'
bspc rule -a Emacs state=tiled
